service: serverless_typescript_boilerplate
provider:
  name: aws
  runtime: nodejs6.10
plugins:
  - serverless-plugin-typescript
  - serverless-offline
include:
  handler.ts
functions:
  webhook:
    handler: handler.webhook
    events:
     - http:
         path: webhook
         method: post